# Generated by Django 4.1 on 2023-03-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('id_file_1', models.FileField(upload_to='id_files/')),
                ('id_file_2', models.FileField(upload_to='id_files/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
