# Generated by Django 4.1 on 2023-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=2000)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('emergency_contact_person', models.CharField(max_length=200)),
                ('emergency_contact_number', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(upload_to='applicant_image/')),
                ('id_card_file_upload_1', models.FileField(upload_to='id_card_files/')),
                ('id_card_file_upload_2', models.FileField(upload_to='id_card_files/')),
            ],
        ),
    ]
